apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hsds-bucket-loader
  name: hsds-bucket-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsds-bucket-loader
  template:
    metadata:
      labels:
        app: hsds-bucket-loader
    spec:
      containers:
        -
          name: bucket-watch
          image: 530483214727.dkr.ecr.us-west-2.amazonaws.com/hsds-bucket-loader:v0.1f
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: bucket-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          env:
          - name: RUN_COMMAND
            value: watch
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_secret_access_key
          - name: HS_USERNAME
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: hs_username
          - name: HS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: hs_password
        -
          name: bucket-load
          image: 530483214727.dkr.ecr.us-west-2.amazonaws.com/hsds-bucket-loader:v0.1f
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: bucket-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          env:
          - name: RUN_COMMAND
            value: load
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_secret_access_key
          - name: HS_USERNAME
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: hs_username
          - name: HS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: hs_password
        -
          name: head
          image: 530483214727.dkr.ecr.us-west-2.amazonaws.com/hsds:v0.1c
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: accounts
            mountPath: "/config/passwd.txt"
            subPath: passwd.txt
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 5101
          env:
          - name: NODE_TYPE
            value: head_node
          - name: TARGET_SN_COUNT
            value: "1"
          - name: TARGET_DN_COUNT
            value: "1"
          - name: K8S_APP_LABEL
            value: null 
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_secret_access_key
        -
          name: sn
          image: 530483214727.dkr.ecr.us-west-2.amazonaws.com/hsds:v0.1c
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: accounts
            mountPath: "/config/passwd.txt"
            subPath: passwd.txt
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 5101
          env:
          - name: NODE_TYPE
            value: sn
          - name: HEAD_ENDPOINT
            value: http://localhost:5100
          - name: K8S_APP_LABEL
            value: null 
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-auth-keys
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-auth-keys
                key: aws_secret_access_key
        -
          name: dn
          image: 530483214727.dkr.ecr.us-west-2.amazonaws.com/hsds:v0.1c
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: accounts
            mountPath: "/config/passwd.txt"
            subPath: passwd.txt
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 6101
          env:
          - name: NODE_TYPE
            value: dn
          - name: HEAD_ENDPOINT
            value: http://localhost:5100
          - name: K8S_APP_LABEL
            value: null 
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-auth-keys
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-auth-keys
                key: aws_secret_access_key
    
      volumes:
      - name: accounts
        secret:
          secretName: user-password
      - name: bucket-config
        configMap:
          name: hsds-bucket-loader-config
      - name: hsds-config
        configMap:
          name: hsds-config
      - name: hsds-override
        configMap:
          name: hsds-override
        
