apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hsds-bucket-loader
  name: hsds-bucket-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsds-bucket-loader
  template:
    metadata:
      labels:
        app: hsds-bucket-loader
    spec:
      serviceAccountName: hsds-eks-policy
      containers:
        -
          name: load
          image: hdfgroup/bucket_loader:v0.2c
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256M"
            limits:
              memory: "512M"
          volumeMounts:
          - name: bucket-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          env:
          - name: RUN_COMMAND
            value: load
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: HS_USERNAME
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: hs_username
          - name: HS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: hs_password
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        -
          name: head
          image: hdfgroup/hsds:v0.6.3i
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128M"
            limits:
              memory: "256M"
          volumeMounts:
          - name: accounts
            mountPath: "/config/passwd.txt"
            subPath: passwd.txt
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 5101
          env:
          - name: NODE_TYPE
            value: head_node
          - name: TARGET_SN_COUNT
            value: "1"
          - name: TARGET_DN_COUNT
            value: "1"
          - name: K8S_APP_LABEL
            value: null
          - name: PASSWORD_FILE
            value: /config/passwd.txt
        -
          name: sn
          image: hdfgroup/hsds:v0.6.3i
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256M"
            limits:
              memory: "512M"
          volumeMounts:
          - name: accounts
            mountPath: "/config/passwd.txt"
            subPath: passwd.txt
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 5101
          env:
          - name: NODE_TYPE
            value: sn
          - name: HEAD_ENDPOINT
            value: http://localhost:5100
          - name: K8S_APP_LABEL
            value: null
          - name: PASSWORD_FILE
            value: /config/passwd.txt
        -
          name: dn
          image: hdfgroup/hsds:v0.6.3i
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256M"
            limits:
              memory: "512M"
          volumeMounts:
          - name: accounts
            mountPath: "/config/passwd.txt"
            subPath: passwd.txt
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 6101
          env:
          - name: NODE_TYPE
            value: dn
          - name: HEAD_ENDPOINT
            value: http://localhost:5100
          - name: K8S_APP_LABEL
            value: null
        -
          name: rangeget
          image: hdfgroup/hsds:v0.6.3i
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256M"
            limits:
              memory: "256M"
          volumeMounts:
          - name: hsds-config
            mountPath: "/config/config.yml"
            subPath: config.yml
          - name: hsds-override
            mountPath: "/config/override.yml"
            subPath: override.yml
          ports:
            -
              containerPort: 6900
          env:
          - name: NODE_TYPE
            value: rangeget
          - name: HEAD_ENDPOINT
            value: http://localhost:5100
          - name: K8S_APP_LABEL
            value: null
      volumes:
      - name: accounts
        secret:
          secretName: user-password
      - name: bucket-config
        configMap:
          name: hsds-bucket-loader-config
      - name: hsds-config
        configMap:
          name: hsds-config
      - name: hsds-override
        configMap:
          name: hsds-override