apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hsds-bucket-loader
  name: hsds-bucket-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsds-bucket-loader
  template:
    metadata:
      labels:
        app: hsds-bucket-loader
    spec:
      containers:
        -
          name: bucket-watch
          image: 530483214727.dkr.ecr.us-west-2.amazonaws.com/hsds-bucket-loader:v0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: "/config/config.yml"
            subPath: config.yml
          env:
          - name: RUN_COMMAND
            value: watch
          - name: PASSWORD_FILE
            value: /config/passwd.txt
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: hs-loader-keys
                key: aws_secret_access_key
      volumes:
      - name: accounts
        secret:
          secretName: user-password
      - name: config
        configMap:
          name: hsds-bucket-loader-config
        
